### ISSUE TITLE
在回滚操作中，是否首先要删除删除现有仓库的全部内容？

### ISSUE THREAD

**Issue by chen-xling** [chen-xling/java_teamwork3#21]
师兄你好！在回滚操作中，是不是应该先删除现有仓库的全部内容，然后再回滚恢复到历史的状态？
@js00070
这样子就需要另外单独写一个函数来删除整个文件夹了。

**Comment by js00070** [comment]
嗯，朴素的实现方式就是这样的，删掉整个工作区，然后从commit里取出对应的完整快照，替换上去

**Comment by chen-xling** [comment]
> 嗯，朴素的实现方式就是这样的，删掉整个工作区，然后从commit里取出对应的完整快照，替换上去

好的谢谢师兄！
