### ISSUE TITLE
完成了任务一和任务二，全都封装成了类，麻烦师兄查看！

### ISSUE THREAD

**Issue by chen-xling** [chen-xling/java_teamwork3#5]
@js00070

**Comment by chen-xling** [comment]
![image](https://user-images.githubusercontent.com/65390850/102113726-53eb7380-3e74-11eb-843a-e5386153cf89.png)
这个是生成的文件夹截图。谢谢师兄！

**Comment by js00070** [comment]
为啥会以哈希值为名称创建文件夹？

**Comment by js00070** [comment]
TeamTask2的gen_file方法，在构建Tree对象的时候，逻辑有点问题。。。

**Comment by chen-xling** [comment]
请问任务二的意思难道不是和任务一差不多，生成相应的文件嘛？只是文件名字改成哈希码

**Comment by chen-xling** [comment]
@js00070 
请问逻辑问题具体是指什么呢，因为我这边测试像是没问题呀

**Comment by js00070** [comment]
> @js00070 
> 请问逻辑问题具体是指什么呢，因为我这边测试像是没问题呀

代码里把tree对象存成了文件夹，tree的value信息不就丢失了吗。。

**Comment by chen-xling** [comment]
> > @js00070
> > 请问逻辑问题具体是指什么呢，因为我这边测试像是没问题呀
> 
> 代码里把tree对象存成了文件夹，tree的value信息不就丢失了吗。。

没有丢失呀。生成了和原来路径文件夹一样的文件夹，里面的子文件夹全都在，blob也在。那我再看看吧，再试着理解一下您要求的任务2是什么意思
