### ISSUE TITLE
上传了新版的任务二代码，类的设计思路都在.java文件里

### ISSUE THREAD

**Issue by chen-xling** [chen-xling/java_teamwork3#7]
@js00070
谢谢师兄！

**Comment by js00070** [comment]
整体逻辑应该是对了，还有一些细节可以改进

**Comment by chen-xling** [comment]
> 整体逻辑应该是对了，还有一些细节可以改进

谢谢师兄！那我再想想怎么继续完善

**Comment by js00070** [comment]
TeamTask2_new_version里的gross_key是用来干什么的？

**Comment by chen-xling** [comment]
> TeamTask2_new_version里的gross_key是用来干什么的？

它就是我根据tree新生成的文件的文件名呀。可以参考我放在main分支里的那份哈希码作为名字的文件。

**Comment by js00070** [comment]
哦哦，看明白了。有以下几点可以改进：

1. 函数gen_tree_file本质上是把tree的内容写到key-value-store里，这里最好是能复用task1的逻辑，因为tree本质上和blob一样，都是key-value-pair，最好是把所有文件操作都封装在task1里，其他地方就不要重复地读写文件了
2. 类名可以改一下，teamtask1、teamtask2这种名称不是很直观
3. 在计算一个文件夹的哈希的时候，其实已经把tree的内容构造过一次了，但编码格式和Tree_content类的output方法的编码方式不一致，最好是能保持一致

**Comment by chen-xling** [comment]
> 哦哦，看明白了。有以下几点可以改进：
> 
> 1. 函数gen_tree_file本质上是把tree的内容写到key-value-store里，这里最好是能复用task1的逻辑，因为tree本质上和blob一样，都是key-value-pair，最好是把所有文件操作都封装在task1里，其他地方就不要重复地读写文件了
> 2. 类名可以改一下，teamtask1、teamtask2这种名称不是很直观
> 3. 在计算一个文件夹的哈希的时候，其实已经把tree的内容构造过一次了，但编码格式和Tree_content类的output方法的编码方式不一致，最好是能保持一致

好的好的，起名困难户再想想办法，继续完善！谢谢师兄！非常感谢阅读！
